version: '3.8'
services:      
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # depends_on:
    #   - server

#   server:
#     build:
#       context: ./server
#       dockerfile: Dockerfile
#     ports:
#       - "3001:3001"
#       - "3002:3002"
#     depends_on:
#       - db

#     environment:
#       DB_HOST: db
#       DB_PORT: 3306
#       DB_USER: root
#       DB_PASSWORD: 1923mitsuyu
#       DB_NAME: cloud_computing_assessment

#   db:
#     image: mysql:8.0
#     environment:
#       MYSQL_ROOT_PASSWORD: 1923mitsuyu
#       MYSQL_DATABASE: cloud_computing_assessment
#     ports:
#       - "3306:3306"
#     volumes:
#       - db_data:/var/lib/mysql
#       - ./initdb:/docker-entrypoint-initdb.d

# volumes:
#   db_data:



