version: '3.8'

services:      
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
      - "3002:3002"
    depends_on:
      - db
      - localstack
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 1923mitsuyu
      DB_NAME: cloud_computing_assessment

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1923mitsuyu
      MYSQL_DATABASE: cloud_computing_assessment
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
   
volumes:
  db_data:

# How to deploy the app to the EC2 instance on Mac
# Mindful that the instance is big enough (midde / large)
# Send the files to EC2
# rsync -avz --progress --exclude='.*' -e "ssh -i ~/Downloads/ikufumi.pem" CAB432_Assessment1 ubuntu@52.65.59.22:/home/ubuntu

# Populate database (manually)
# Access MySQL CLI : sudo docker-compose exec db mysql -u root -p
# Run the SQL Script : 
# USE cloud_computing_assessment;
# SOURCE /docker-entrypoint-initdb.d/schema.sql;

# Check .envfile. It may be hidden. 
# Change the ip address in the endpoints if needed 

# Include the ipadress inside cors so the address will not be blocked

# Hit URL with the ip address of the instance
# http://ec2-54-206-119-162.ap-southeast-2.compute.amazonaws.com:3000

